name: 'vsTest Action'
description: 'Because the offical microsoft/vstest-action is crap' # TODO: Better description needed!
author: 'Brian Welsh (@brian-welsh)'

# Define your inputs here.
inputs:
  repository: 
    default: ${{ github.repository }}
    required: true
    description: > 
      should be self-evident what this is. Normally this would need no other value.

  token:
    default: ${{ github.token }}
    required: true
    description: > 
      should be self-evident what this is. Normally this would need no other value.

  octopus-cli-version:
    required: false
    description: >
      if not provided the latest version will be installed and used. 

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  pre: ../../../dist/package-octopus-pre-action/index.js
  main: ../../../dist/package-octopus-action/index.js
  # post: ../../dist/vstest-action/index.js