name: 'Setup Action'
description: 'Setup Action' # TODO: Better description needed!
author: 'Brian Welsh (@brian-welsh)'

# Define your inputs here.
inputs:
  repository: 
    default: ${{ github.repository }}
    required: true
    description: > 
      should be self-evident what this is. Normally this would need no other value.

  token:
    default: ${{ github.token }}
    required: true
    description: > 
      should be self-evident what this is. Normally this would need no other value.

  config-file:
    required: true
    description: >
      path to a YAML config file 
      TBD format TBD

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  pre: ../../dist/setup-action/index.js