name: Lint Code Base

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - main
# For now, we are not going to run just because we pushed any branch
#  push:
#    branches-ignore:
#      - main

jobs:
  lint:
    if: github.actor == 'dependabot[bot]'
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint Code Base
        id: super-linter
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
